version: 0.1
phases:
  install:
    commands:
    - pip install pytest requests
  pre_build:
    commands:
    - cd sam-app ; python -m pytest tests/ -v
  build:
    commands:
    - cd sam-app ; pip install -r requirements.txt -t hello_world/build/
    - cd sam-app ; cp hello_world/*.py hello_world/build/
  post_build:
    commands:
    # env var BUILD_ARTIFACT_BUCKET is defined in ci.yaml
    - aws cloudformation package
      --template-file sam-app/template.yaml
      --s3-bucket $BUILD_ARTIFACT_BUCKET
      --output-template-file SamDeploymentTemplate.yaml
artifacts:
  type: zip
  files:
  - SamDeploymentTemplate.yaml